### ISSUE TITLE
Make identifiers implementation independent, describing unambiguous identifiers naming rules

### ISSUE THREAD

**Issue by stratosn** [vtl-sdmx-task-force/sdmx-vtl#15]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
PL-CSO-6|UM|47|1587
***
The implementation dependency is not necessary in this case. It leaves possibility of acquiring different result of executing same VTL program under different implementations.
Describe unambiguous identifiers naming rules. e.g.  unquoted identifiers are never the same as quoted.

**Comment by bellomarini** [comment]
I agree that implementation dependency could be avoided in this case. Please refer to #14 , where case-insensitiveness is proposed for identifiers, components, variable parameters.

Quotes could be used just to avoid clashes between the names of the identifiers and keywords and reserved words, yet, I wouldn't introduce case-sensitiveness in quotes.

Moreover, the use of quotes should be explicitly discouraged in order to avoid scarcely readable code.

**Comment by stratosn** [comment]
Discussed under issue #15. Closed as duplicate.
